# ========================================
# BINANCE WEBSOCKET CONFIGURATION
# ========================================

# WebSocket bağlantı adresi
binance.websocket.url=wss://data-stream.binance.vision/stream

# Bağlantı timeout süresi (saniye)
binance.connection.timeout=15

# WebSocket header
binance.user-agent=Mozilla/5.0

# WebSocket origin
binance.origin=https://www.binance.com


# ========================================
# BINANCE SYMBOLS
# ========================================

binance.symbols=btcusdt,ethusdt,bnbusdt,solusdt,xrpusdt,adausdt,dogeusdt,avaxusdt,dotusdt,linkusdt,maticusdt,ltcusdt,trxusdt,atomusdt,nearusdt,uniusdt,aptusdt,suiusdt,filusdt,etcusdt,xlmusdt,algousdt,aaveusdt,icpusdt,arbusdt,opusdt,injusdt,pepeusdt,shibusdt,wifusdt

screen.btc= true
screen.performance= true
